#! /usr/bin/env ruby

# This file is part of TransitTime
#
# TransitTime is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TransitTime is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Nibbles.  If not, see <http://www.gnu.org/licenses/>.

$KCODE="UTF-8"
USER_ROOT = ENV["HOME"]+"/.transittime"
TT_ROOT = File.expand_path("#{File.dirname(__FILE__)}")
TT_LIB = "#{TT_ROOT}/lib"
TT_ICONS = "#{TT_ROOT}/icons"

require "rubygems"
require "ruby-debug"


#if not File.exists?(USER_ROOT) or not File.exists?(USER_ROOT+'/tt.sqlite3')
#  puts "Creating .tt directory and DB..."
#  system "mkdir #{USER_ROOT} "
#end

#if not File.exists?(USER_ROOT+'/configuration')
#  puts "Creating configuration file..."
#  system "cp #{TT_ROOT}/configuration.example #{USER_ROOT}/configuration"
#end

#require "#{TT_LIB}/configuration"
#Configuration.load("#{USER_ROOT}/configuration")

#Dir.chdir USER_ROOT

require "#{TT_LIB}/window"

# set things up
ENV['RAILS_ENV'] ||= 'development' unless Device.hildon?
ENV['RAILS_ENV'] ||= 'production'  if Device.hildon?


require "config/boot"
require "config/environment"

begin
  require 'app/controller/place_dialogue'

  pd = PlaceDialogue.new

  Gtk.main 

rescue Exception => exception
  File.open "/tmp/tt.error_log", "a+" do |log|
    log.write Time.now.to_s + "\n"
    log.write exception.message + "\n"
    log.write exception.backtrace.join("\n") + "\n\n"
  end

  puts exception.class
  puts exception.message
  puts exception.backtrace.join("\n") + "\n\n"
end
